#!/bin/bash

########### RHCE294 - BRIGHT DELALI-GAGLOH - adhoc  ###################

#### User automation is created on all inventory hosts ######

echo "Creating User automation on all inventory hosts"
 
ansible -u root all  -m raw -a "useradd -G wheel automation"

echo "    "


#### Copy SSH key to all hosts, store it in /home/automation/.ssh/authourized_keys ####

echo "Copying SSH Key to all hosts"

ansible -u root all -m authorized_key -a "user='automation' state='present' key='{{ lookup('file','/home/automation/.ssh/id_rsa.pub')}}'"

echo "    "

####### privilege elevation for automation user #######

echo "Allowing Privilege elevation for automation user"

ansible -u root all -m raw -a "echo 'automation ALL=(ALL) NOPASSWD: ALL > /etc/sudoers.d/automation'"

