#!/bin/bash

######################################################## TASK 1 ###############################################################################
## Create an SSH keypair. Write a script /home/automation/plays/adhoc that uses Ansible ad-hoc commands to achieve the following:            ## 
## User automation is created on all inventory hosts.                                                                                        ##
## SSH key (that you generated) is copied to all inventory hosts for the automation user and stored in /home/automation/.ssh/authorized_keys.##
## The automation user is allowed to elevate privileges on all inventory hosts without having to provide a password.                         ##
## After running the adhoc script, you should be able to SSH into all inventory hosts using the automation user without password, as well    ##
## as a run all privileged commands.                                                                                                         ##
###############################################################################################################################################



########### RHCE294 - BRIGHT DELALI-GAGLOH - adhoc  ###################

#### User automation is created on all inventory hosts ######

echo "Creating User automation on all inventory hosts"
 
ansible -u root all  -m raw -a "useradd -G wheel automation"

echo "    "


#### Copy SSH key to all hosts, store it in /home/automation/.ssh/authourized_keys ####

echo "Copying SSH Key to all hosts"

ansible -u root all -m authorized_key -a "user='automation' state='present' key='{{ lookup('file','/home/automation/.ssh/id_rsa.pub')}}'"

#ansible -u root all -m raw -a "user='automation' state='present' key='{{ lookup('file','/home/automation/.ssh/id_rsa.pub')}}'"

echo "    "

####### privilege elevation for automation user #######

echo "Allowing Privilege elevation for automation user"

ansible -u root all -m raw -a "echo 'automation ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/automation"

